package feeds

import (
	"encoding/xml"
	"fmt"
	"html"
	"strings"
	"time"

	"gofetchrss/internal/store"
)

// ---------- RSS 2.0 ----------

type rss struct {
	XMLName xml.Name   `xml:"rss"`
	Version string     `xml:"version,attr"`
	Channel rssChannel `xml:"channel"`
}
type rssChannel struct {
	Title       string    `xml:"title"`
	Link        string    `xml:"link"`
	Description string    `xml:"description"`
	Generator   string    `xml:"generator,omitempty"`
	PubDate     string    `xml:"pubDate,omitempty"`
	Items       []rssItem `xml:"item"`
}
type rssItem struct {
	Title       string `xml:"title"`
	Link        string `xml:"link"`
	GUID        string `xml:"guid"`
	PubDate     string `xml:"pubDate"`
	Description string `xml:"description,omitempty"`
}

func BuildRSS(site store.Site, items []store.Item) (string, error) {
	ch := rssChannel{
		Title:       site.Name,
		Link:        site.URL,
		Description: fmt.Sprintf("Generated by GoFetchRSS from %s", site.URL),
		Generator:   "GoFetchRSS",
	}
	if len(items) > 0 {
		ch.PubDate = items[0].PublishedAt.UTC().Format(time.RFC1123Z)
	}
	for _, it := range items {
		desc := it.ContentHTML
		if desc == "" {
			desc = html.EscapeString(it.Title)
		}
		ch.Items = append(ch.Items, rssItem{
			Title:       it.Title,
			Link:        it.URL,
			GUID:        it.URL,
			PubDate:     it.PublishedAt.UTC().Format(time.RFC1123Z),
			Description: desc,
		})
	}
	out, err := xml.MarshalIndent(rss{Version: "2.0", Channel: ch}, "", "  ")
	if err != nil {
		return "", err
	}
	return xml.Header + string(out), nil
}

// ---------- Atom ----------

type atomFeed struct {
	XMLName xml.Name   `xml:"feed"`
	Xmlns   string     `xml:"xmlns,attr"`
	Title   string     `xml:"title"`
	ID      string     `xml:"id"`
	Updated string     `xml:"updated"`
	Link    []atomLink `xml:"link"`
	Entries []atomEntry `xml:"entry"`
}
type atomLink struct {
	Href string `xml:"href,attr"`
	Rel  string `xml:"rel,attr,omitempty"`
}
type atomEntry struct {
	Title     string   `xml:"title"`
	ID        string   `xml:"id"`
	Updated   string   `xml:"updated"`
	Published string   `xml:"published,omitempty"`
	Link      atomLink `xml:"link"`
	Content   atomContent `xml:"content,omitempty"`
}
type atomContent struct {
	Type string `xml:"type,attr"`
	Body string `xml:",innerxml"`
}

func BuildAtom(site store.Site, items []store.Item, selfURL string) (string, error) {
	updated := time.Now().UTC()
	if len(items) > 0 {
		updated = items[0].PublishedAt.UTC()
	}
	f := atomFeed{
		Xmlns:   "http://www.w3.org/2005/Atom",
		Title:   site.Name,
		ID:      site.URL,
		Updated: updated.Format(time.RFC3339),
		Link: []atomLink{
			{Href: selfURL, Rel: "self"},
			{Href: site.URL, Rel: "alternate"},
		},
	}
	for _, it := range items {
		body := it.ContentHTML
		if body == "" {
			body = html.EscapeString(it.Title)
		}
		f.Entries = append(f.Entries, atomEntry{
			Title:     it.Title,
			ID:        it.URL,
			Updated:   it.PublishedAt.UTC().Format(time.RFC3339),
			Published: it.PublishedAt.UTC().Format(time.RFC3339),
			Link:      atomLink{Href: it.URL, Rel: "alternate"},
			Content:   atomContent{Type: "html", Body: body},
		})
	}
	out, err := xml.MarshalIndent(f, "", "  ")
	if err != nil {
		return "", err
	}
	return xml.Header + string(out), nil
}

// ---------- JSON Feed 1.1 ----------

func BuildJSON(site store.Site, items []store.Item, feedURL string) string {
	var b strings.Builder
	b.WriteString(`{"version":"https://jsonfeed.org/version/1.1","title":`)
	writeJSONString(&b, site.Name)
	b.WriteString(`,"home_page_url":`)
	writeJSONString(&b, site.URL)
	b.WriteString(`,"feed_url":`)
	writeJSONString(&b, feedURL)
	b.WriteString(`,"items":[`)
	for i, it := range items {
		if i > 0 {
			b.WriteByte(',')
		}
		b.WriteString(`{"id":`)
		writeJSONString(&b, it.URL)
		b.WriteString(`,"title":`)
		writeJSONString(&b, it.Title)
		b.WriteString(`,"url":`)
		writeJSONString(&b, it.URL)
		b.WriteString(`,"date_published":`)
		writeJSONString(&b, it.PublishedAt.UTC().Format(time.RFC3339))
		if it.ContentHTML != "" {
			b.WriteString(`,"content_html":`)
			writeJSONString(&b, it.ContentHTML)
		}
		b.WriteString(`}`)
	}
	b.WriteString(`]}`)
	return b.String()
}

func writeJSONString(b *strings.Builder, s string) {
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			b.WriteString(`\"`)
		case '\\':
			b.WriteString(`\\`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			if r < 0x20 {
				fmt.Fprintf(b, `\u%04x`, r)
			} else {
				b.WriteRune(r)
			}
		}
	}
	b.WriteByte('"')
}

// ---------- OPML ----------

func BuildOPML(sites []store.Site, baseURL string) string {
	var b strings.Builder
	b.WriteString(xml.Header)
	b.WriteString(`<opml version="2.0"><head><title>GoFetchRSS Export</title></head><body>`)
	for _, s := range sites {
		fmt.Fprintf(&b, `<outline type="rss" text=%s title=%s xmlUrl=%s htmlUrl=%s/>`,
			quoteAttr(s.Name), quoteAttr(s.Name),
			quoteAttr(strings.TrimSuffix(baseURL, "/")+"/feeds/"+s.ID+".xml"),
			quoteAttr(s.URL))
	}
	b.WriteString(`</body></opml>`)
	return b.String()
}

func quoteAttr(s string) string { return `"` + html.EscapeString(s) + `"` }
